#!/usr/bin/env node
// take-reading.mjs — THE ONE COMMAND FOR THE DAY A NEW DATED READING IS TAKEN.
//
//   npm run census:reading        # on or after NOT_BEFORE. Before that it refuses and touches nothing.
//
// ═══ ⛔ NOTHING RUNS BEFORE 2026-09-25 — AND THE DATE IS THE POINT, NOT A DELAY ════════════════
// The third reading is deliberately a fortnight after the second, matching the 08-27 → 09-11
// interval, so the two new pairs (`08-27..09-25`, `09-11..09-25`) span comparable gaps. The
// harvester keys its file on the DATE and refuses to overwrite, which is the guard that makes the
// set trustworthy: date-keyed and immutable. ⛔ Do NOT add a time component to get a same-day
// third reading past it — a fortnight was chosen, and a 10-hour interval answers nothing.
//
// ═══ ⭐ THE METHOD IS harvest-index.mjs, BYTE FOR BYTE. THIS FILE ADDS NOTHING TO IT. ═══════════
// This wrapper spawns the harvester and inherits its verdict. It sends no parameter, applies no
// filter, projects no field. The three rules that produced the two earlier readings live THERE:
//   · NO `siwx` parameter in either direction — the CLI's silent `siwx=false` hid every testnet row
//   · DISCARD, never publish, unless Base Sepolia AND Polygon Amoy both appear
//   · NO `.toLowerCase()` on payTo — base58 is case-sensitive; that discarded the first 09-11 run
//
// ═══ ⭐⭐⭐ WHY A THIRD READING EXISTS — RECORDED HERE SO IT IS NOT RE-DERIVED ON THE DAY ═════════
// Every two-reading diff on this site says "unchanged ≠ stable": equal at two instants is not the
// same as unmoved in between. A third reading is the first instrument that can put a NUMBER on
// that caveat. The number that matters is
//
//     how many keys were UNCHANGED across 08-27..09-11 and then CHANGED by 09-25
//
// — that is how many keys the first pair would have called settled that were not, i.e. whether a
// pair ever misled us. The mirror number — equal at 08-27 and 09-25 but different at 09-11 — is
// how many keys the SPAN pair calls unchanged while the middle reading saw them move. Both are
// computed by `stabilityAcrossThree` in shared/x402-diff.mjs, defined and fixture-tested before
// the third harvest existed. This command prints them the moment the harvest lands.
//
// ═══ WHAT THIS COMMAND CANNOT DO, AND SAYS SO ══════════════════════════════════════════════════
// The diff route and the snapshot page import harvests STATICALLY, and the snapshot page carries
// hand-written, MEASURED prose per date. Neither can be pre-wired for a file that does not exist
// yet, and neither should be generated by a script. So after the harvest this prints the exact
// wiring steps (anchored on symbols, not line numbers), and the rest of the day is a session with
// tests, a commit, a deploy and `gate:deployed` — the same as the second reading.

import { spawnSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import { stabilityAcrossThree, pairsFor } from "../../shared/x402-diff.mjs";

// ⛔ Not exported: importing this module RUNS it (top-level guard, then a spawn). Tests spawn it instead.
const NOT_BEFORE = "2026-09-25";
const HERE = new URL("./", import.meta.url);
const today = new Date().toISOString().slice(0, 10);

const harvestsOnDisk = () =>
  readdirSync(HERE).filter((f) => /^circle-index-\d{4}-\d{2}-\d{2}\.harvest\.json$/.test(f)).sort();
const dateOf = (f) => f.slice("circle-index-".length, "circle-index-".length + 10);

// ── 0. the date guard ─────────────────────────────────────────────────────────────────────────
if (today < NOT_BEFORE) {
  console.error(`✖ take-reading — today is ${today}, and the next reading is not before ${NOT_BEFORE}.`);
  console.error(`  Nothing was fetched and nothing was written. The interval is the point; see the header.`);
  process.exit(3);
}

const before = harvestsOnDisk();
console.log(`take-reading — ${today}. ${before.length} dated reading(s) on disk: ${before.map(dateOf).join(", ") || "none"}\n`);

// ── 1. the harvest, by the harvester, with its own verdict ────────────────────────────────────
const r = spawnSync(process.execPath, [new URL("./harvest-index.mjs", import.meta.url).pathname], { stdio: "inherit" });
if (r.status !== 0) {
  console.error(`\n✖ take-reading — harvester exited ${r.status}. It wrote nothing; there is nothing to wire.`);
  process.exit(r.status ?? 2);
}

const after = harvestsOnDisk();
const fresh = after.filter((f) => !before.includes(f));
if (fresh.length !== 1) {
  // ⛔ The harvester said 0 but the directory did not gain exactly one file. Refuse to reason about it.
  console.error(`\n✖ take-reading — expected exactly one new harvest file, found ${fresh.length}: ${fresh.join(", ")}`);
  process.exit(2);
}
console.log(`\n✅ new reading: ${fresh[0]}`);

// ── 2. the number the third reading exists to produce ─────────────────────────────────────────
const dates = after.map(dateOf);
if (after.length >= 3) {
  const [fa, fb, fc] = after.slice(-3);
  const load = (f) => JSON.parse(readFileSync(new URL(`./${f}`, import.meta.url), "utf8"));
  const s = stabilityAcrossThree(load(fa), load(fb), load(fc), { labelA: dateOf(fa), labelB: dateOf(fb), labelC: dateOf(fc) });
  console.log(`\n── unchanged ≠ stable — ${dateOf(fa)} → ${dateOf(fb)} → ${dateOf(fc)} ──────────────────────────`);
  if (!s.computed) {
    console.error(`✖ NOT COMPUTED — ${s.gate.refusal}`);
    process.exit(4);
  }
  for (const field of ["payTo", "amount"]) {
    const m = s[field];
    console.log(`  ${field.padEnd(7)} comparable keys ${m.comparable}`);
    console.log(`          unchanged across all three          ${m.unchangedAcrossAllThree}`);
    console.log(`     ⭐   unchanged ${dateOf(fa)}..${dateOf(fb)}, then changed by ${dateOf(fc)}   ${m.unchangedThenChanged}   ← did the first pair mislead`);
    console.log(`     ⭐   equal at ${dateOf(fa)} and ${dateOf(fc)}, different at ${dateOf(fb)}   ${m.changedThenReverted}   ← did the span pair mislead`);
    console.log(`          changed then held / changed twice     ${m.changedThenHeld} / ${m.changedTwice}   (partition ${m.partitions ? "sums" : "DOES NOT SUM"})`);
  }
  console.log(`\n  pairMisled  byFirstPair ${s.pairMisled.byFirstPair}   bySpanPair ${s.pairMisled.bySpanPair}`);
  console.log(`  ⛔ zero in both is silence over these keys at these instants — it is not "stable".`);
} else {
  console.log(`\n  (${after.length} reading(s) on disk — the three-way measure needs three.)`);
}

// ── 3. what is left for the session, anchored on symbols ──────────────────────────────────────
const D = dateOf(fresh[0]);
console.log(`
── wiring — a session with tests, not a script ─────────────────────────────────
  pairs after wiring: ${pairsFor(dates).join("  ")}
  1. netlify/functions/snapshot-diff.mjs — import ${fresh[0]} beside EARLIER/LATER; add "${D}" to
     HARVESTS and LABEL. PAIRS/NEWEST_PAIR derive from that; netlify.toml's :pair rules need nothing.
  2. netlify/functions/snapshot.mjs — a SNAPSHOTS["${D}"] entry with MEASURED figures from the file
     (listingsCollected, acceptsRows, selfCheck.observed). DATES/LATEST/PAIRS derive; /built derives.
  3. the three-way numbers above belong on the ${dates.at(-2)}..${D} page under its existing
     "unchanged is not stable" <h2> — stabilityAcrossThree is already in the JSON contract's module.
  4. npm run test:all — verify-snapshot-diff §0 asserts the snapshot dates and harvest dates agree,
     so a harvest with no page, or a page with no harvest, goes red there.
  5. commit · netlify deploy --prod · npm run gate:deployed (5/5, served tree == this tree).
`);
