// _shell.mjs — the shared frame for the public evidence pages (site/evidence/*, served on tikpema.xyz).
//
// ═══ ⭐ WHAT THESE PAGES ARE ═════════════════════════════════════════════════════════════════
// Static HTML a stranger can open with no account, generated by a script from DATA (a signed report, or
// a set of quorum reads) — never hand-written. Every sentence on a page is a function of a field, so a
// page cannot say something its data does not.
//
// ⛔ WHAT THEY MUST NEVER DO (the scope, 2026-10-02): no score, no grade, no ranking, no recommendation,
// no claim that a vault is safe. COLOUR ENCODES CERTAINTY, NEVER GOODNESS: "the owner can move your
// assets" is ESTABLISHED and is drawn exactly like any other established fact — no green tick, no red.
// `BANNED` below is asserted against every generated page by test:evidence.
//
// ⚠️ SELF-CONTAINED, like the /dd discovery page: no external CSS, fonts, scripts or images. A page whose
// job is "check this without trusting us" must not depend on a CDN we chose.

export const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");

/** Words that turn an inventory into a verdict. Matched case-insensitively as whole words in the
 *  rendered page's VISIBLE text (markup and attribute values stripped). The pages SAY that they carry no
 *  score, rating or recommendation, so those exact phrases are allowed only inside disclaimer elements,
 *  `<p class="not-this">`, which the check removes before matching. Nothing else may use that class. */
export const BANNED = [
  "safe", "safer", "safest", "unsafe", "risky", "riskier", "risk score", "risk level", "low risk", "high risk",
  "score", "scored", "grade", "rating", "rated", "rank", "ranked", "ranking", "recommend", "recommended",
  "recommendation", "trusted", "trustworthy", "secure", "dangerous", "warning", "verdict", "passed", "failed",
  "error", "n/a", "audited", "approved",
];

/** Visible text of a page, minus the disclaimer element(s). Exported so the suite and the builders check
 *  the SAME thing. */
export function visibleTextForBanCheck(html) {
  return html
    .replace(/<p class="not-this">[\s\S]*?<\/p>/g, " ")
    .replace(/<style[\s\S]*?<\/style>/g, " ")
    .replace(/<script[\s\S]*?<\/script>/g, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&[a-z#0-9]+;/gi, " ");
}

export function bannedWordsIn(html) {
  const text = visibleTextForBanCheck(html).toLowerCase();
  return BANNED.filter((w) => new RegExp(`(^|[^a-z0-9])${w.replace(/[/]/g, "\\/")}([^a-z0-9]|$)`).test(text));
}

/** A JSON-RPC call as a command anyone can paste. */
export function curlFor(endpoint, method, params) {
  const body = JSON.stringify({ jsonrpc: "2.0", id: 1, method, params });
  return `curl -s -X POST ${endpoint} -H 'Content-Type: application/json' -d '${body}'`;
}

export const fmtInt = (n) => BigInt(n).toLocaleString("en-US");

/** 6-decimal token units → "84,807,145.54" (2 places, truncated, never rounded up). */
export function fmtUnits6(raw) {
  const v = BigInt(raw);
  const whole = v / 1_000_000n;
  const cents = (v % 1_000_000n) / 10_000n;
  return `${whole.toLocaleString("en-US")}.${cents.toString().padStart(2, "0")}`;
}

/** ⭐ THE ONE DATE FORMAT on every evidence page: "2026-10-02 20:23 UTC" (T, 2026-10-03). Every date a reader sees goes
 *  through this; test:evidence fails on an ISO "T…Z" stamp in visible text. */
export const fmtUtc = (unixSeconds) => new Date(Number(unixSeconds) * 1000).toISOString().slice(0, 16).replace("T", " ") + " UTC";
/** Same format from an ISO string (e.g. a build's verifiedAt). */
export const fmtUtcIso = (iso) => fmtUtc(Date.parse(iso) / 1000);
export const isoUtc = fmtUtc; // legacy name, same single format

/**
 * The two answer states. ⭐ SAME VISUAL WEIGHT: a "not established" row is not an error (no red) and not
 * "not applicable" (no grey). It differs only in its marker: a dashed outline and a "?" instead of a solid
 * mark. Its text colour is the same as an established row's.
 */
export const mark = {
  established: `<span class="m m-est" title="Established">■ Established</span>`,
  notEstablished: `<span class="m m-not" title="Not established">? Not established</span>`,
};

/** A collapsible block of commands. */
export function commands(list) {
  if (!list.length) return "";
  // ⛔ EVERY COMMAND STATES ITS ANSWER (T, 2026-10-03): running a command needs nothing unstated; CHECKING its answer
  // must not either. A command with no expected answer hands the reader raw hex and leaves the decoding to them.
  for (const c of list) {
    if (!c.expect || !c.read) throw new Error(`commands(): "${c.label}" has no ${!c.expect ? "expected answer" : "how-to-read line"}; every printed command must state both`);
  }
  return `<details class="cmds"><summary>Check this yourself (${list.length} command${list.length === 1 ? "" : "s"})</summary>
${list.map((c) => `<div class="cmd">${c.label ? `<div class="cmd-label">${esc(c.label)}</div>` : ""}<pre><code>${esc(c.command)}</code></pre><div class="cmd-expect">Expected: <code>${esc(c.expect)}</code></div><div class="cmd-read">How to read it: ${esc(c.read)}</div></div>`).join("\n")}
</details>`;
}


// ═══ ⭐⭐ AGE: COMPUTED BY THE VIEWER'S BROWSER, NEVER BY THE BUILD ═════════════════════════════
// A static page cannot know how old it is when it is READ; only the reader's clock can. So the build
// writes the block's time (a fact) and the page computes the age at view time. The DATA never refreshes:
// past STALE_AFTER_DAYS a banner says how old it is and that it describes that block, not today.
// Without JavaScript the absolute date is still printed at the top: the fallback is a stated "as of",
// never silence. ⭐ `ageOf` is ONE function: inlined into the page by its own source text and imported
// by test:evidence, so what the suite tests is what the browser runs.
export const STALE_AFTER_DAYS = 7;

/** (block unix seconds, now ms, threshold days) → { days, stale, text }. days null = cannot tell. */
export function ageOf(blockTs, nowMs, staleAfterDays) {
  var secs = nowMs / 1000 - Number(blockTs);
  if (!(Number(blockTs) > 0) || !isFinite(secs) || secs < -300) return { days: null, stale: false, text: "" };
  var days = Math.max(0, Math.floor(secs / 86400));
  var text = days === 0 ? "less than a day old" : days === 1 ? "1 day old" : days + " days old";
  return { days: days, stale: days >= staleAfterDays, text: text };
}

/**
 * The "as of" line, the banner slot and the script that fills them.
 * @param blockTs   unix seconds of the block the data describes
 * @param asOfHtml  the always-visible sentence (no JS needed). It MUST contain "{age}" exactly once, at the point the age
 *                  belongs (T, 2026-10-03): the age is placed inside the sentence it qualifies, never appended after
 *                  whatever happens to come last.
 * @param afterHtml an optional separate sentence, in its own paragraph, that the age does NOT apply to
 * @param staleHtml the banner body; `{age}` is replaced in the browser with e.g. "9 days old"
 */
export function ageBlock({ blockTs, asOfHtml, afterHtml = "", staleHtml, staleAfterDays = STALE_AFTER_DAYS }) {
  if (asOfHtml.split("{age}").length !== 2) throw new Error('ageBlock(): asOfHtml must contain "{age}" exactly once');
  return `<p class="asof" data-block-ts="${Number(blockTs)}" data-stale-days="${Number(staleAfterDays)}">${asOfHtml.replace("{age}", '<span class="age-rel"></span>')}</p>${afterHtml ? `\n<p class="asof">${afterHtml}</p>` : ""}
<div class="stale" hidden data-template="${esc(staleHtml)}"></div>
<script>(function(){var ageOf=${ageOf.toString()};
var el=document.querySelector("[data-block-ts]");if(!el)return;
var a=ageOf(el.getAttribute("data-block-ts"),Date.now(),Number(el.getAttribute("data-stale-days")));
if(a.days===null)return;
el.querySelector(".age-rel").textContent=", "+a.text+" by this device's clock";
if(a.stale){var b=document.querySelector(".stale");b.innerHTML=b.getAttribute("data-template").split("{age}").join(a.text);b.hidden=false;}
})();</script>`;
}

const CSS = `
:root{--ink:#0f141a;--ink2:#161d25;--line:#2a333d;--paper:#ece6d8;--dim:#a9a293;--amber:#e0a44c}
@media (prefers-color-scheme: light){:root:not([data-theme="dark"]){--ink:#f7f3ea;--ink2:#efe9dc;--line:#d6cdbb;--paper:#1b1f24;--dim:#5d5649;--amber:#9a6412}}
:root[data-theme="light"]{--ink:#f7f3ea;--ink2:#efe9dc;--line:#d6cdbb;--paper:#1b1f24;--dim:#5d5649;--amber:#9a6412}
*{box-sizing:border-box}
html,body{margin:0;background:var(--ink);color:var(--paper)}
body{font:16px/1.6 Georgia,"Times New Roman",serif;padding:32px 16px 64px}
main{max-width:760px;margin:0 auto}
h1{font-size:1.75rem;line-height:1.25;margin:.2em 0 .4em;font-weight:600}
h2{font-size:1.2rem;margin:2.2em 0 .6em;padding-top:.8em;border-top:1px solid var(--line);font-weight:600}
.eyebrow{font:12px/1.4 ui-monospace,Menlo,Consolas,monospace;letter-spacing:.08em;text-transform:uppercase;color:var(--amber)}
.sub{color:var(--dim)}
code,.mono{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:.86em;overflow-wrap:anywhere}
a{color:var(--amber)}
.asof{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:.9rem;margin:.4em 0 1em}
.stale{border:2px solid var(--paper);padding:12px 16px;margin:12px 0 16px;font-weight:600}
.stale[hidden]{display:none}
.notice{border:1px solid var(--line);border-left:3px solid var(--amber);background:var(--ink2);padding:12px 16px;margin:16px 0}
.notice p{margin:.3em 0}
.prov{background:var(--ink2);border:1px solid var(--line);padding:12px 16px;margin:16px 0}
.prov p{margin:.4em 0}
.summary{margin:16px 0}
.summary p{margin:.35em 0}
.r-count{color:var(--dim);font-size:.95em}
.row{border:1px solid var(--line);padding:12px 16px;margin:10px 0;background:var(--ink)}
.row.not{border-style:dashed}
.row p{margin:.35em 0}
.q{font-weight:600}
.m{display:inline-block;font:12px/1.6 ui-monospace,Menlo,Consolas,monospace;padding:0 8px;border:1px solid var(--paper);color:var(--paper);margin-bottom:4px}
.m-not{border-style:dashed}
.reach{color:var(--dim);font-size:.95em}
details.cmds{margin:.6em 0 0}
details.cmds summary{cursor:pointer;color:var(--amber);font-size:.92em}
.cmd{margin:.6em 0}
.cmd-label,.cmd-expect,.cmd-read{font-size:.88em;color:var(--dim)}
.howto{font-size:.92em;border-left:3px solid var(--amber);padding:6px 12px;margin:16px 0}
pre{background:var(--ink2);border:1px solid var(--line);padding:10px;overflow-x:auto;margin:.3em 0;white-space:pre-wrap;word-break:break-all}
blockquote{margin:.6em 0;padding:0 0 0 12px;border-left:2px solid var(--line);color:var(--dim)}
table{border-collapse:collapse;width:100%;font-size:.92em}
td,th{border-bottom:1px solid var(--line);padding:6px 8px;text-align:left;vertical-align:top}
footer .not-this{color:var(--dim)}
footer{margin-top:3em;padding-top:1em;border-top:1px solid var(--line);color:var(--dim);font-size:.9em}
`;

/** The one line a stranger needs before the first command (T, 2026-10-03). Inserted ONCE, directly above the first
 *  command block, so it sits where the reader first needs it. */
export const HOWTO_RUN = "Each command needs only curl in a macOS or Linux terminal (on Windows: WSL or Git Bash). No key, no account, no settings.";
export function withHowTo(body) {
  const i = body.indexOf('<details class="cmds">');
  if (i === -1) return body;
  const j = body.lastIndexOf('<div class="row', i);
  const at = j === -1 ? i : j;
  return body.slice(0, at) + `<p class="howto">${esc(HOWTO_RUN)}</p>\n` + body.slice(at);
}

export function page({ title, description, body }) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<meta name="robots" content="noindex">
<style>${CSS}</style>
</head>
<body>
<main>
${withHowTo(body)}
</main>
</body>
</html>
`;
}

/**
 * A quorum JSON-RPC reader for the BUILD scripts: every call goes to every endpoint; the answers must be
 * byte-identical, or the call THROWS (never picks a winner, never returns a partial). Each call is recorded
 * with one paste-able command per endpoint, so the page can print exactly what was asked.
 */
export function quorumReader(endpoints) {
  const log = [];
  const one = async (endpoint, method, params) => {
    const res = await fetch(endpoint, {
      method: "POST", headers: { "content-type": "application/json" },
      body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }),
    });
    if (!res.ok) throw new Error(`${endpoint} ${method}: HTTP ${res.status}`);
    return res.json();
  };
  async function read(method, params, { allowRevert = false } = {}) {
    const answers = await Promise.all(endpoints.map((e) => one(e, method, params)));
    const norm = answers.map((a) => (a.error ? { error: { code: a.error.code, data: a.error.data ?? null } } : { result: a.result }));
    const first = JSON.stringify(norm[0]);
    for (let i = 1; i < norm.length; i++) {
      if (JSON.stringify(norm[i]) !== first) {
        throw new Error(`endpoints disagree on ${method} ${JSON.stringify(params)}: ${norm.map((n) => JSON.stringify(n)).join(" vs ")}`);
      }
    }
    if (norm[0].error && !allowRevert) throw new Error(`${method} ${JSON.stringify(params)} returned an error on every endpoint: ${first}`);
    const entry = {
      method, params, answer: norm[0],
      commands: endpoints.map((e) => ({ endpoint: e, command: curlFor(e, method, params) })),
    };
    log.push(entry);
    return entry;
  }
  /** Each endpoint's head. Heads legitimately differ by a block or two, so this is NOT a quorum read and is
   *  never stated as a fact: it only chooses a block that every endpoint has, for the reads that are. */
  async function lowestHead() {
    const heads = await Promise.all(endpoints.map((e) => one(e, "eth_blockNumber", [])));
    for (const h of heads) if (h.error || !h.result) throw new Error(`a head was unreadable: ${JSON.stringify(h)}`);
    return heads.map((h) => BigInt(h.result)).reduce((a, b) => (a < b ? a : b));
  }
  return { read, lowestHead, log, endpoints };
}
