#!/usr/bin/env node
// stage-ledger.mjs — TAIL of deploy:prod. `git add` exactly the two ledgers the chain just appended to.
//
//   node scripts/stage-ledger.mjs     (npm run stage:ledger — last link of deploy:prod)
//
// INDEX ONLY. This never commits, never pushes, never touches history — the commit is the human's, with
// the human's message. It stages the paths in LEDGERS (gate-ledger.mjs — one list, one place) and nothing
// else: not the build stamp (its committed value is null BY DESIGN and it is regenerated by `npm run
// build` every deploy), not any other dirty file. Staging is safe to run late in a chain: if anything
// before it failed, this step never runs and the index is untouched; if this step runs, the deploy has
// already been verified (gate:deployed) and captured (capture:window, gate:deployloss).
//
// ⚠️ It WARNS when shared/build-stamp.generated.mjs is dirty — the generated stamp has been committed by
// mistake twice before; `npm run stamp:clear` before the commit.
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { LEDGERS } from "./gate-ledger.mjs";

const STAMP = "shared/build-stamp.generated.mjs";
const git = (...a) => execFileSync("git", a, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();

const present = LEDGERS.map((l) => l.path).filter((p) => existsSync(p));
if (present.length === 0) { console.log("stage-ledger: no ledger files present — nothing staged"); process.exit(0); }
git("add", "--", ...present);
const staged = git("diff", "--cached", "--name-only").split("\n").filter(Boolean);
const stagedLedgers = staged.filter((p) => present.includes(p));
console.log(`ledger staged — commit it (${stagedLedgers.length ? stagedLedgers.join(", ") : "no ledger changes to stage"})`);
const stampDirty = git("status", "--porcelain", "--", STAMP) !== "";
if (stampDirty) console.log(`⚠️ ${STAMP} is dirty (non-null generated stamp) — it was NOT staged; run \`npm run stamp:clear\` before you commit so it is not swept in.`);
// ⚠️ THE INDEX IS NOW POPULATED. `git add` is additive: the next `git add <anything> && git commit`
// would carry these two along (625f7fd). The pre-commit hook refuses that mix; this line makes the
// happy path one paste so the hook never has to fire.
if (stagedLedgers.length) {
  console.log(`\n⚠️ The index now holds these ${stagedLedgers.length} ledger file(s). Commit them BEFORE you stage anything else — the pre-commit hook refuses a mixed commit:\n`);
  console.log(`  git commit -m "chore(ledger): deploy captures — refusal window + loss sweep"\n`);
}
