#!/usr/bin/env node
// stamp-build.mjs — bake provenance INTO the deployed artifact.
//
// ═══ WHY THIS EXISTS ═════════════════════════════════════════════════════════════════════════
// Netlify records `commit_ref: null`, `build_id: null` and `commit_message: null` on every CLI
// deploy (`deploy_source: "cli"`, no build runs). Verified against the API on 2026-07-29 for
// every deploy made that day. So the platform CANNOT tell you which commit is serving prod, and
// on 2026-07-29 that gap hid a promotion that never landed: a hotfix build served for 7.5 hours
// while the repo, the suites and the handoff all said Option D was live.
//
// `netlify deploy --dir=dist` ships the WORKING TREE, not a commit. So a commit SHA alone is not
// enough either — it describes what you meant to deploy, not what you did. Three fields together:
//
//   commit  — HEAD at stamp time. What you meant to ship.
//   dirty   — did the deployed surface have uncommitted edits? If true, `commit` is a LABEL and
//             not an identity, and nothing may be concluded from it alone.
//   tree    — sha256 over the actual bytes of everything deployable. THIS is the identity. It can
//             be recomputed at any commit and compared, which is the only real binding available.
//
// ⭐ THE COMMITTED VALUE OF THE GENERATED FILE MUST STAY `null`. A deploy that skipped stamping
// then self-reports UNRESOLVED rather than a stale, confident, wrong SHA. That is the same rule
// as resolveBuildId in shared/dd-canary/health.mjs: never return a placeholder on failed
// resolution, because any constant compares equal to itself and re-opens the exact fail-open the
// version binding was built to close. `scripts/verify-blobs-probe.mjs` asserts it.
//
// Restore it after deploying:  node scripts/stamp-build.mjs --clear

import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "shared", "build-stamp.generated.mjs");

/** Everything Netlify actually deploys as function code. `dist/` is excluded on purpose: it is a
 *  build OUTPUT, so hashing it would make the stamp depend on the build it is stamping. */
const SURFACES = ["netlify/functions", "shared"];

/** Excluded from BOTH the tree hash and the dirty check — hashing the stamp into itself is
 *  circular, and its own regeneration is not source drift. */
const SELF = "shared/build-stamp.generated.mjs";

const HEADER = `// GENERATED by scripts/stamp-build.mjs — DO NOT EDIT, DO NOT COMMIT A NON-NULL VALUE.
//
// Committed state is \`null\` on purpose: a deploy that skipped stamping must self-report
// UNRESOLVED, never a stale SHA. \`npm run build\` regenerates this; \`npm run stamp:clear\`
// restores the null. See scripts/stamp-build.mjs for the full reasoning.
`;

const emit = (value) =>
  `${HEADER}\nexport const RAW_BUILD_STAMP = ${value === null ? "null" : JSON.stringify(value, null, 2)};\n`;

if (process.argv.includes("--clear")) {
  writeFileSync(OUT, emit(null), "utf8");
  console.log("build stamp CLEARED -> null (unresolved)");
  process.exit(0);
}

const gitRaw = (args) => {
  try {
    return execFileSync("git", args, { cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
  } catch {
    return null; // not a repo, or git unavailable — resolves to null, never a placeholder
  }
};

const git = (args) => {
  const out = gitRaw(args);
  return out === null ? null : out.trim();
};

const walk = (dir, acc = []) => {
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return acc;
  }
  for (const name of entries.sort()) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, acc);
    else acc.push(full);
  }
  return acc;
};

// Content hash of every deployable byte, path-sensitive and order-independent.
// A rename changes it; a whitespace edit changes it; regenerating this file does not.
const files = SURFACES.flatMap((s) => walk(join(ROOT, s)))
  .map((f) => relative(ROOT, f).split("\\").join("/"))
  .filter((p) => p !== SELF)
  .sort();

const tree = createHash("sha256");
for (const p of files) {
  tree.update(p, "utf8");
  tree.update("\0", "utf8");
  tree.update(createHash("sha256").update(readFileSync(join(ROOT, p))).digest("hex"), "utf8");
  tree.update("\n", "utf8");
}

const commit = git(["rev-parse", "HEAD"]);

// Dirty is scoped to the DEPLOYED SURFACE and ignores the stamp itself. Untracked scratch files
// elsewhere in the tree are not deploy drift and must not raise a false alarm — a dirty flag that
// cries wolf is a dirty flag people learn to ignore.
// ⚠️ gitRaw, NOT git. Porcelain v1 lines are `XY <path>` — the status columns are POSITIONAL and
// column 1 is a space for an unstaged change. Trimming the whole blob eats that leading space on
// the FIRST line only, shifting its path by one character so the SELF comparison silently misses
// and the stamp reports itself as drift. Caught by its own output: it printed
// "hared/build-stamp.generated.mjs". A dirty flag that cries wolf is one people learn to ignore.
const porcelain = gitRaw(["status", "--porcelain", "--", ...SURFACES]);
const dirtyPaths =
  porcelain === null
    ? null
    : porcelain
        .split("\n")
        .filter((l) => l.length > 3)
        .map((l) => l.slice(3).trim())
        .filter((p) => p && p !== SELF);

const stamp = {
  commit,
  dirty: dirtyPaths === null ? null : dirtyPaths.length > 0,
  dirtyCount: dirtyPaths === null ? null : dirtyPaths.length,
  tree: tree.digest("hex"),
  fileCount: files.length,
  generatedAt: new Date().toISOString(),
};

writeFileSync(OUT, emit(stamp), "utf8");

console.log("build stamp written:");
console.log(`  commit     ${stamp.commit ?? "(unresolved)"}`);
console.log(`  dirty      ${stamp.dirty}${stamp.dirtyCount ? ` (${stamp.dirtyCount} path(s))` : ""}`);
console.log(`  tree       ${stamp.tree}`);
console.log(`  files      ${stamp.fileCount}`);
if (stamp.dirty) {
  console.log("\n  ⚠️  DEPLOYED SURFACE IS DIRTY — `commit` is a label, not an identity.");
  for (const p of dirtyPaths) console.log(`      ${p}`);
}
